gogs:
  restart: always
  image: gogs/gogs-rpi:0.9.97
  volumes:
   - /home/rubemlrm/data/gogs:/data
  ports:
   - "3000:3000"
   - "2222:22"

web:
  restart: always
  build: ./nginx/
  volumes:
   - /home/rubemlrm/data/nginx/logs:/var/log/nginx
  ports:
    - "80:80"
  links:
   - gogs

