web:
  restart: always
  build: ./docker/services/nginx/
  volumes:
   - ./docker/logs/nginx:/var/log/nginx
   - ./site:/usr/src/
  ports:
    - "80:80"
  links:
   - php

php:
  restart: always
  build: ./docker/services/php/
  volumes:
    - ./site:/usr/src/
  links:
    - db

db:
  restart: always
  image: mysql:latest
  volumes:
    - ./docker/data/database:/var/lib/mysql
  ports:
    - "3306:3306"
  env_file:
    - ./docker/.env